name: My First Workflow

on:
  push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Show Date
        run: date

      - name: Show Files
        run: ls

      - name: Show Current Directory
        run: pwd